telegram:
  username:
  token:
  chat-id:

binance:
  core:
    base-url: api.binance.com
    #    https://api-gcp.binance.com
    #    https://api1.binance.com
    #    https://api2.binance.com
    #    https://api3.binance.com
    #    https://api4.binance.com
    api-key:
    secret-key:
  path:
    time: /api/v3/time
    order: /api/v3/order
    withdraw: /sapi/v1/capital/withdraw/apply
    balance: /sapi/v1/capital/config/getall

bitget:
  core:
    base-url: https://api.bitget.com
    #    https://capi.bitget.com
    api-key:
    secret-key:
    passphrase:
  path:
    order: /api/spot/v1/trade/orders
